package it.unisalento.rest.distributori.domain;
// Generated 24-mag-2017 22.56.53 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Set prodottos = new HashSet(0);
	private Set categorieFornites = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String nome) {
		this.nome = nome;
	}

	public Categoria(String nome, Set prodottos, Set categorieFornites) {
		this.nome = nome;
		this.prodottos = prodottos;
		this.categorieFornites = categorieFornites;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getProdottos() {
		return this.prodottos;
	}

	public void setProdottos(Set prodottos) {
		this.prodottos = prodottos;
	}

	public Set getCategorieFornites() {
		return this.categorieFornites;
	}

	public void setCategorieFornites(Set categorieFornites) {
		this.categorieFornites = categorieFornites;
	}

}
