package it.unisalento.rest.distributori.domain;
// Generated 13-apr-2017 14.28.49 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Distributore generated by hbm2java
 */
public class Distributore implements java.io.Serializable {

	private Integer id;
	private Dipendente dipendente;
	private BigDecimal lat;
	private BigDecimal lon;
	private String indirizzo;
	private String posizioneEdificio;
	private Integer stato;
	private Integer numScaffali;
	private Integer numPosti;
	private Set acquistas = new HashSet(0);
	private Set categorieFornites = new HashSet(0);
	private Set prodottiErogatis = new HashSet(0);
	private Set manutienes = new HashSet(0);
	private Set rifornisces = new HashSet(0);

	public Distributore() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Dipendente getDipendente() {
		return this.dipendente;
	}

	public void setDipendente(Dipendente dipendente) {
		this.dipendente = dipendente;
	}

	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	public BigDecimal getLon() {
		return this.lon;
	}

	public void setLon(BigDecimal lon) {
		this.lon = lon;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getPosizioneEdificio() {
		return this.posizioneEdificio;
	}

	public void setPosizioneEdificio(String posizioneEdificio) {
		this.posizioneEdificio = posizioneEdificio;
	}

	public Integer getStato() {
		return this.stato;
	}

	public void setStato(Integer stato) {
		this.stato = stato;
	}

	public Integer getNumScaffali() {
		return this.numScaffali;
	}

	public void setNumScaffali(Integer numScaffali) {
		this.numScaffali = numScaffali;
	}

	public Integer getNumPosti() {
		return this.numPosti;
	}

	public void setNumPosti(Integer numPosti) {
		this.numPosti = numPosti;
	}

	public Set getAcquistas() {
		return this.acquistas;
	}

	public void setAcquistas(Set acquistas) {
		this.acquistas = acquistas;
	}

	public Set getCategorieFornites() {
		return this.categorieFornites;
	}

	public void setCategorieFornites(Set categorieFornites) {
		this.categorieFornites = categorieFornites;
	}

	public Set getProdottiErogatis() {
		return this.prodottiErogatis;
	}

	public void setProdottiErogatis(Set prodottiErogatis) {
		this.prodottiErogatis = prodottiErogatis;
	}

	public Set getManutienes() {
		return this.manutienes;
	}

	public void setManutienes(Set manutienes) {
		this.manutienes = manutienes;
	}

	public Set getRifornisces() {
		return this.rifornisces;
	}

	public void setRifornisces(Set rifornisces) {
		this.rifornisces = rifornisces;
	}

}
