package it.unisalento.rest.distributori.domain;
// Generated 4-mag-2017 23.58.49 by Hibernate Tools 4.3.1.Final

/**
 * ProdottiErogati generated by hbm2java
 */
public class ProdottiErogati implements java.io.Serializable {

	private Integer id;
	private Distributore distributore;
	private Prodotto prodotto;
	private Integer scaffale;
	private Integer posto;
	private Integer quantita;

	public ProdottiErogati() {
	}

	public ProdottiErogati(Distributore distributore, Prodotto prodotto) {
		this.distributore = distributore;
		this.prodotto = prodotto;
	}

	public ProdottiErogati(Distributore distributore, Prodotto prodotto, Integer scaffale, Integer posto,
			Integer quantita) {
		this.distributore = distributore;
		this.prodotto = prodotto;
		this.scaffale = scaffale;
		this.posto = posto;
		this.quantita = quantita;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Distributore getDistributore() {
		return this.distributore;
	}

	public void setDistributore(Distributore distributore) {
		this.distributore = distributore;
	}

	public Prodotto getProdotto() {
		return this.prodotto;
	}

	public void setProdotto(Prodotto prodotto) {
		this.prodotto = prodotto;
	}

	public Integer getScaffale() {
		return this.scaffale;
	}

	public void setScaffale(Integer scaffale) {
		this.scaffale = scaffale;
	}

	public Integer getPosto() {
		return this.posto;
	}

	public void setPosto(Integer posto) {
		this.posto = posto;
	}

	public Integer getQuantita() {
		return this.quantita;
	}

	public void setQuantita(Integer quantita) {
		this.quantita = quantita;
	}

}
