package it.unisalento.rest.distributori.domain;
// Generated 24-mag-2017 22.56.53 by Hibernate Tools 4.3.1.Final

/**
 * SottoscrizioniDistributori generated by hbm2java
 */
public class SottoscrizioniDistributori implements java.io.Serializable {

	private Integer id;
	private Distributore distributore;
	private Persona persona;

	public SottoscrizioniDistributori() {
	}

	public SottoscrizioniDistributori(Distributore distributore, Persona persona) {
		this.distributore = distributore;
		this.persona = persona;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Distributore getDistributore() {
		return this.distributore;
	}

	public void setDistributore(Distributore distributore) {
		this.distributore = distributore;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
